import {
  parseOwnerRepo,
  getRepoInfo,
  getBranchSha,
  createBranch,
  upsertFile,
  createPullRequest,
} from "./github-api";

const DOCS_PATH = "docs/intake.md";

export interface CreateDocsPRParams {
  repoUrl: string;
  updatedReport: string;
  commitHash: string;
  changedFiles: string[];
  changedSections: string[];
  summary: string;
}

export interface CreateDocsPRResult {
  prUrl: string;
  prNumber: number;
  branch: string;
}

/**
 * Opens (or reuses) a PR on the target GitHub repo containing the
 * regenerated intake.md, for human review — RepoIntel never auto-merges.
 */
export async function createDocsPR(params: CreateDocsPRParams): Promise<CreateDocsPRResult> {
  const { owner, repo } = parseOwnerRepo(params.repoUrl);
  const shortSha = params.commitHash.slice(0, 8);
  const branchName = `docs/update-${shortSha}`;

  const repoInfo = await getRepoInfo(owner, repo);
  const baseBranch = repoInfo.default_branch;
  const baseSha = await getBranchSha(owner, repo, baseBranch);

  await createBranch(owner, repo, branchName, baseSha);

  await upsertFile(
    owner,
    repo,
    DOCS_PATH,
    params.updatedReport,
    branchName,
    `docs: Update documentation for commit ${shortSha}`
  );

  const title = `docs: Update documentation for changes in ${params.changedFiles.slice(0, 3).join(", ")}${
    params.changedFiles.length > 3 ? `, +${params.changedFiles.length - 3} more` : ""
  }`;

  const body = [
    `Automated documentation update triggered by commit \`${params.commitHash}\`.`,
    "",
    "**Changed sections:**",
    ...params.changedSections.map((s) => `- ${s}`),
    "",
    `**Summary:** ${params.summary}`,
    "",
    "**Files changed in this push:**",
    ...params.changedFiles.slice(0, 30).map((f) => `- \`${f}\``),
    params.changedFiles.length > 30 ? `- ...and ${params.changedFiles.length - 30} more` : "",
    "",
    "Please review and approve to merge. This PR was auto-generated by [RepoIntel](https://github.com/) — nothing merges automatically.",
  ]
    .filter((line) => line !== "")
    .join("\n");

  const pr = await createPullRequest(owner, repo, {
    title,
    body,
    head: branchName,
    base: baseBranch,
  });

  return { prUrl: pr.url, prNumber: pr.number, branch: branchName };
}
